package org.ploxie.vulkan.image;

import static org.lwjgl.vulkan.VK10.*;

import lombok.Getter;

public enum VulkanImageLayout {

	UNDEFINED(VK_IMAGE_LAYOUT_UNDEFINED),
	GENERAL(VK_IMAGE_LAYOUT_GENERAL),
	COLOR_ATTACHMENT_OPTIMAL(VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL),
	DEPTH_STENCIL_ATTACHMENT_OPTIMAL(VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL),
	DEPTH_STENCIL_READ_ONLY_OPTIMAL(VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL),
	SHADER_READ_ONLY_OPTIMAL(VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL),
	TRANSFER_SRC_OPTIMAL(VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL),
	TRANSFER_DST_OPTIMAL(VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL),
	PREINITIALIZED(VK_IMAGE_LAYOUT_PREINITIALIZED);
	
	@Getter
	private int bitMask;

	VulkanImageLayout(int bitMask) {
		this.bitMask = bitMask;
	}
	
}
