package org.ploxie.vulkan.image;

import lombok.Getter;
import static org.lwjgl.vulkan.VK10.*;

public enum VulkanImageUsageFlag {

	TRANSFER_SRC(VK_IMAGE_USAGE_TRANSFER_SRC_BIT),
	TRANSFER_DST(VK_IMAGE_USAGE_TRANSFER_DST_BIT),
	SAMPLED(VK_IMAGE_USAGE_SAMPLED_BIT),
	STORAGE(VK_IMAGE_USAGE_STORAGE_BIT),
	COLOR_ATTACHMENT(VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT),
	DEPTH_STENCIL(VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT),
	TRANSIENT_ATTACHMENT(VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT),
	INPUT_ATTACHMENT(VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT);
	
	@Getter
	private int bitMask;

	VulkanImageUsageFlag(int bitMask) {
		this.bitMask = bitMask;
	}
	
}
